version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16 # Specify the runtime (e.g., Node.js, Python, Java, etc.)
    commands:
      - echo Installing dependencies...
      - npm install # Replace with `pip install` or other commands for your project

  pre_build:
    commands:
      - echo Running pre-build commands...
      - npm run lint # Example: lint your code (optional)

  build:
    commands:
      - echo Building the project...
      - npm run build # Replace with your build command
      - echo Build completed successfully.

  post_build:
    commands:
      - echo Running post-build commands...
      - echo Build phase complete.

artifacts:
  files:
    - '**/*'  # Include all files and folders
  discard-paths: yes
  base-directory: build  # Directory where your build artifacts are located (adjust as necessary)

cache:
  paths:
    - 'node_modules/**/*' # Cache dependencies (adjust based on your project)

